name: Scrape UK Football Matches

on:
  schedule:
    - cron: '0 1 * * 1' # every Monday at 01:00 UTC
  workflow_dispatch: # allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npm run scrape

      - name: Commit matches.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add matches.json
          git commit -m "Update matches.json" || echo "No changes to commit"
          git push
